name: Automated Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Empty Output File for Test 1
        run: touch test_data/test1_actual.txt

      - name: Run Test 1
        run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt

      - name: Compare Test 1 Results
        run: diff test_data/test1_actual.txt test_data/test1_expected.txt

      - name: Create Empty Output File for Test 2
        run: touch test_data/test2_actual.txt

      - name: Run Test 2
        run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt

      - name: Compare Test 2 Results
        run: diff test_data/test2_actual.txt test_data/test2_expected.txt

      - name: Create Empty Output File for Test 3
        run: touch test_data/test3_actual.txt

      - name: Run Test 3
        run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt

      - name: Compare Test 3 Results
        run: diff test_data/test3_actual.txt test_data/test3_expected.txt
